# Generated by Django 2.2.28 on 2022-06-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ReddirectUserTable',
            fields=[
                ('link_num', models.AutoField(primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
