# Generated by Django 2.2.28 on 2022-06-12 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reddirectusertable_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reddirectusertable',
            old_name='link_num',
            new_name='id',
        ),
    ]
