# Generated by Django 2.2.28 on 2022-06-12 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20220613_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reddirectusertable',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.ReddirectId', unique=True),
        ),
    ]
