# Generated by Django 2.2.28 on 2022-06-12 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_auto_20220613_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReddirectAnonymous',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.ReddirectId', unique=True)),
                ('url', models.URLField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RenameModel(
            old_name='ReddirectUserTable',
            new_name='ReddirectUser',
        ),
        migrations.AlterModelManagers(
            name='reddirectid',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='counterfolder',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
